package com.ntg.CitizenLink.enums;

public enum EventType {
    // Authentication Events
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    PASSWORD_CHANGE,
    PASSWORD_CHANGE_FAILURE,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_COMPLETE,

    // User Management Events
    USER_CREATE,
    USER_CREATE_FAILURE,
    USER_UPDATE,
    USER_UPDATE_FAILURE,
    USER_DELETE,
    USER_DELETE_FAILURE,
    USER_ENABLE,
    USER_DISABLE,
    ROLE_CHANGE,

    // Case Management Events
    CASE_CREATE,
    CASE_CREATE_FAILURE,
    CASE_UPDATE,
    CASE_UPDATE_FAILURE,
    CASE_ASSIGN,
    CASE_STATUS_CHANGE,
    CASE_NOTE_ADD,

    // Data Access Events
    REPORT_VIEW,
    REPORT_EXPORT,
    DOCUMENT_UPLOAD,
    DOCUMENT_UPLOAD_FAILURE,
    DOCUMENT_DOWNLOAD,
    DOCUMENT_DELETE,

    // System Events
    SYSTEM_ERROR,
    CONFIG_CHANGE,
    PERFORMANCE_ALERT
}
