package com.ntg.CitizenLink.entities;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(
    name = "attachment",
    indexes = {
        @Index(name = "idx_attachment_case_id", columnList = "case_id")
    }
)
public class Attachment {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "case_id", nullable = false, updatable = false)
    private Case caseEntity;

    /**
     * The filename as uploaded by the user. Stored for display only.
     * Never used as a filesystem path — use storedFileName for that.
     */
    @Column(name = "original_file_name", nullable = false, length = 500)
    private String originalFileName;

    /**
     * UUID-based filename used on disk (e.g. "550e8400-e29b-41d4-a716-446655440000.pdf").
     * Prevents path traversal attacks. Generated by FileStorageService before saving.
     */
    @Column(name = "stored_file_name", nullable = false, length = 500)
    private String storedFileName;

    /**
     * Validated MIME type. Allowed: application/pdf, image/png, image/jpeg,
     * application/vnd.openxmlformats-officedocument.wordprocessingml.document.
     * Validated by FileStorageService — never trust the client-supplied value.
     */
    @Column(name = "mime_type", nullable = false, length = 100)
    private String mimeType;

    /**
     * File size in bytes. Max 5 MB = 5_242_880 bytes, enforced before saving.
     */
    @Column(name = "file_size_bytes", nullable = false)
    private long fileSizeBytes;

    /**
     * Absolute path to the file on the server filesystem (or relative path
     * from the configured storage root). Set by FileStorageService.
     * Never expose this path in API responses.
     */
    @Column(name = "storage_path", nullable = false, length = 1000)
    private String storagePath;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "uploaded_by_user_id", nullable = false, updatable = false)
    private AppUser uploadedByUser;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false,
            columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetDateTime createdAt;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    protected Attachment() {}

    // -------------------------------------------------------------------------
    // Getters & Setters
    // -------------------------------------------------------------------------

    public UUID getId() { return id; }

    public Case getCaseEntity() { return caseEntity; }
    public void setCaseEntity(Case caseEntity) { this.caseEntity = caseEntity; }

    public String getOriginalFileName() { return originalFileName; }
    public void setOriginalFileName(String originalFileName) { this.originalFileName = originalFileName; }

    public String getStoredFileName() { return storedFileName; }
    public void setStoredFileName(String storedFileName) { this.storedFileName = storedFileName; }

    public String getMimeType() { return mimeType; }
    public void setMimeType(String mimeType) { this.mimeType = mimeType; }

    public long getFileSizeBytes() { return fileSizeBytes; }
    public void setFileSizeBytes(long fileSizeBytes) { this.fileSizeBytes = fileSizeBytes; }

    public String getStoragePath() { return storagePath; }
    public void setStoragePath(String storagePath) { this.storagePath = storagePath; }

    public AppUser getUploadedByUser() { return uploadedByUser; }
    public void setUploadedByUser(AppUser uploadedByUser) { this.uploadedByUser = uploadedByUser; }

    public OffsetDateTime getCreatedAt() { return createdAt; }
}
