package com.ntg.citizenlink.entities;


import jakarta.persistence.*;
import com.ntg.citizenlink.enums.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(
    name = "cases",
    uniqueConstraints = {
        @UniqueConstraint(name = "uq_cases_case_number", columnNames = "case_number")
    },
    indexes = {
        @Index(name = "idx_cases_status",              columnList = "status"),
        @Index(name = "idx_cases_type",                columnList = "type"),
        @Index(name = "idx_cases_priority",            columnList = "priority"),
        @Index(name = "idx_cases_citizen_id",          columnList = "citizen_id"),
        @Index(name = "idx_cases_department_id",       columnList = "department_id"),
        @Index(name = "idx_cases_assigned_to_user_id", columnList = "assigned_to_user_id"),
        @Index(name = "idx_cases_created_at",          columnList = "created_at"),
        @Index(name = "idx_cases_due_at",              columnList = "due_at")
    }
)
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class Case {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * Optimistic-lock version. Incremented by Hibernate on every UPDATE;
     * concurrent writers that read a stale version fail at commit with
     * ObjectOptimisticLockingFailureException (-> 409), preventing
     * lost-update corruption from two simultaneous transitions.
     */
    @Version
    @Column(name = "version", nullable = false)
    private long version;

    /**
     * Human-readable business identifier. Format: CASE-{YYYY}-{00001}.
     * Generated by CaseService using the case_number_seq table before insert.
     * Never auto-generated by JPA — always set explicitly in the service layer.
     */
    @Column(name = "case_number", nullable = false, length = 30, updatable = false)
    private String caseNumber;

    @Column(name = "subject", nullable = false, length = 255)
    private String subject;

    @Column(name = "description", nullable = false, columnDefinition = "TEXT")
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 20)
    private CaseType type;

    @Enumerated(EnumType.STRING)
    @Column(name = "priority", nullable = false, length = 10)
    private Priority priority;

    /**
     * Status is always NEW on creation and transitions only through
     * CaseService.transition(). Never set this field directly from a
     * request body — doing so bypasses workflow validation entirely.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private CaseStatus status = CaseStatus.NEW;

    @Enumerated(EnumType.STRING)
    @Column(name = "channel", nullable = false, length = 20)
    private Channel channel;

    /**
     * Required when transitioning to RESOLVED. Stored on the case record
     * so it is immediately accessible without joining status_history.
     */
    @Column(name = "resolution_summary", columnDefinition = "TEXT")
    private String resolutionSummary;

    @Column(name = "due_at", columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetDateTime dueAt;

    // -------------------------------------------------------------------------
    // Relationships
    // -------------------------------------------------------------------------

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "citizen_id", nullable = false, updatable = false)
    private Citizen citizen;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "department_id", nullable = false)
    private Department department;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "created_by_user_id", nullable = false, updatable = false)
    private AppUser createdByUser;

    /**
     * Nullable — a case starts unassigned (status NEW) until a SUPERVISOR assigns it.
     * Intentionally left unchanged when the assigned user is deactivated.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assigned_to_user_id")
    private AppUser assignedToUser;

    // -------------------------------------------------------------------------
    // Timestamps
    // -------------------------------------------------------------------------

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false,
            columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false,
            columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetDateTime updatedAt;

    /**
     * Set automatically by CaseService when status transitions to RESOLVED.
     * Not settable via API request body.
     */
    @Column(name = "resolved_at", columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetDateTime resolvedAt;

    /**
     * Set automatically by CaseService when status transitions to CLOSED.
     * Not settable via API request body.
     */
    @Column(name = "closed_at", columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetDateTime closedAt;
}
